
[functions.scrape_profile_apify]
enabled = true
verify_jwt = true
import_map = "./functions/scrape_profile_apify/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/scrape_profile_apify/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/scrape_profile_apify/*.html" ]
